---
ansible_user: root
mosaico_domain: mosaico.cheysson.fr
mosaico_smtp_server: ssl0.ovh.net
mosaico_smtp_port: 587
mosaico_smtp_user: contact@leilachaibi.fr
mosaico_smtp_password: "{{ vaulted_smtp_password }}"
mosaico_mail_from_name: Leila Chaibi
mosaico_mail_from_address: contact@leilachaibi.fr
mosaico_web_users:
  - username: leila
    password: "{{ vaulted_password }}"
    templates:
      - leila-mail
mosaico_secret: "{{ vaulted_mosaico_secret }}"
letsencrypt_email: arthur@cheysson.fr
